[package]
name = "webhook-testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
truelayer-rust = {git = "https://github.com/TrueLayer/truelayer-rust"}
json = "*"
anyhow = "*"
reqwest = { version = "*", features = ["blocking"] }
serde_json = "*"
clap = { version = "*", features = ["derive"]}